[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "insights.js"
to = "https://swetrix.org/swetrix.js"
status = 200

[[redirects]]
from = "/insights/"
to = "https://api.swetrix.com/log"
status = 200
