[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "insight.js"
to = "https://swetrix.org/swetrix.js"
status = 200

[[redirects]]
from = "/insight/"
to = "https://api.swetrix.com/log"
status = 200
